assert.o: assert.c
britney-py.o: britney-py.c dpkg.h templates.h memory.h
checklib.o: checklib.c dpkg.h templates.h memory.h
dpkg.o: dpkg.c dpkg.h templates.h memory.h
freelist.o: freelist.c templates.h memory.h
memory2.o: memory2.c
memory3.o: memory3.c memory.h templates.h freelist.h
memory.o: memory.c memory.h templates.h freelist.h
dpkg-lib.o: dpkg-lib.cpp dpkg.h templates.h memory.h
Makefile.dep : Makefile assert.c britney-py.c checklib.c dpkg.c freelist.c memory2.c memory3.c memory.c dpkg.h freelist.h memory.h templates.h
